In [1]:
import numpy as np
import pandas as pd
import re
import requests
from bs4 import BeautifulSoup

In [2]:
title = []
year = []
certificate = []
runtime = []
genre = []
rating = []
metascore = []
director = []
stars = []
votes = []
gross = []

In [ ]:
for i in range(1,11):
    url = f"https://www.imdb.com/list/ls098063263/?sort=list_order,asc&st_dt=&mode=detail&page={i}"
    page = requests.get(url)
    soup = BeautifulSoup(page.text)
    
    for t in soup.find_all('h3',class_ = 'lister-item-header'):
        text = t.text
        regex_title = re.findall('\d+\.\s([a-zA-Z0-9].+)',text)
        if regex_title:
            title.append(regex_title[0])
        else:
            title.append(np.nan)
            
    for y in soup.find_all('h3',class_ = 'lister-item-header'):
        text = y.text
        regex_year = re.findall('\((\d+)\)',text)
        if regex_year:
            year.append(regex_year[0])
        else:
            year.append(np.nan)
    
    for c in soup.find_all('div',class_ = 'lister-item mode-detail'):
        cer = c.find('span',class_ = 'certificate')
        if cer:
            certificate.append(cer.text)
        else:
            certificate.append(np.nan)
        
    for r in soup.find_all('div',class_ = 'lister-item mode-detail'):
        time = r.find('span',class_ = 'runtime')
        if time:
            runtime.append(time.text)
        else:
            runtime.append(np.nan)
        
    for g in soup.find_all('div',class_ = 'lister-item mode-detail'):
        gen = g.find('span',class_ = 'genre').text
        regex_genre = re.findall('\w+',gen)
        if regex_genre:
            genre.append(regex_genre[0])
        else:
            genre.append(np.nan)
        
    for ra in soup.find_all('div',class_ = 'lister-item mode-detail'):
        rate = ra.find('span',class_ = 'ipl-rating-star__rating')
        if rate:
            rating.append(rate.text)
        else:
            rating.append(np.nan)
        
    for m in soup.find_all('div',class_ = 'lister-item mode-detail'):
        meta = m.find('div',class_ = 'inline-block ratings-metascore')
        if meta:
            regex_meta = re.findall('\d+',meta.text)
            metascore.append(regex_meta[0])
        else:
            metascore.append(np.nan)
        
    for d in soup.find_all('div',class_ = 'lister-item mode-detail'):
        dire = d.text
        regex_dire = re.findall('tors?:\n(.+)',dire)
        if regex_dire:
            director.append(regex_dire[0])
        else:
            director.append(np.nan)
        
    for s in soup.find_all('div',class_ = 'lister-item mode-detail'):
        st = s.text
        regex_st = re.findall('tars:\n(.+)\n',st)
        if regex_st:
            stars.append(regex_st[0])
        else:
            stars.append(np.nan)
        
    for v in soup.find_all('div',class_ = 'lister-item mode-detail'):
        vote = v.text
        regex_vote = re.findall('Votes:\n(.+)\n',vote)
        if regex_vote:
            votes.append(regex_vote[0])
        else:
            votes.append(np.nan)
        
    for g in soup.find_all('div',class_ = 'lister-item mode-detail'):
        gr = g.text
        regex_gr = re.findall('e Gross:\s\$(.+)',gr)
        if regex_gr:
            gross.append(regex_gr[0])
        else:
            gross.append(np.nan)

In [4]:
dic = {'Title':title,
      'Release_year':year,
      'Certificate':certificate,
      'Rating':rating,
      'Runtime(min)':runtime,
      'Genre':genre,
      'Metascore':metascore,
      'Director':director,
      'Stars':stars,
      'Votes':votes,
      'Gross($)':gross}

In [ ]:
df = pd.DataFrame(dic)

In [6]:
df

,Title,Release_year,Certificate,Rating,Runtime(min),Genre,Metascore,Director,Stars,Votes,Gross($)
0,Avatar,2009,UA,7.9,162 min,Action,83,James Cameron,"Sam Worthington,","1,358,356","2,923,706,026"
1,Avengers: Endgame,2019,UA,8.4,181 min,Action,78,"Anthony Russo,","Robert Downey Jr.,","1,207,990","2,799,439,100"
2,Avatar: The Way of Water,2022,UA,7.6,192 min,Action,67,James Cameron,"Sam Worthington,","451,677","2,320,250,281"
3,Titanic,1997,UA,7.9,194 min,Drama,75,James Cameron,"Leonardo DiCaprio,","1,243,170","2,264,743,305"
4,Star Wars: Episode VII - The Force Awakens,2015,U,7.8,138 min,Action,80,J.J. Abrams,"Daisy Ridley,","954,671","2,071,310,218"
...,...,...,...,...,...,...,...,...,...,...,...
995,Daredevil,2003,UA,5.3,103 min,Action,42,Mark Steven Johnson,"Ben Affleck,","225,491","179,179,718"
996,City Slickers,1991,NaN,6.8,113 min,Comedy,70,Ron Underwood,"Billy Crystal,","61,042","179,033,791"
997,He's Just Not That Into You,2009,13,6.4,129 min,Comedy,47,Ken Kwapis,"Ginnifer Goodwin,","179,057","178,866,158"
998,Eagle Eye,2008,A,6.6,118 min,Action,43,D.J. Caruso,"Shia LaBeouf,","192,271","178,767,383"
999,Along Came Polly,2004,UA,6,90 min,Comedy,44,John Hamburg,"Ben Stiller,","141,076","178,311,729"

In [7]:
df.isnull().sum()

Title            0
Release_year     0
Certificate     50
Rating           0
Runtime(min)     0
Genre            0
Metascore       38
Director         0
Stars            0
Votes            0
Gross($)         0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         1000 non-null   object
 1   Release_year  1000 non-null   object
 2   Certificate   950 non-null    object
 3   Rating        1000 non-null   object
 4   Runtime(min)  1000 non-null   object
 5   Genre         1000 non-null   object
 6   Metascore     962 non-null    object
 7   Director      1000 non-null   object
 8   Stars         1000 non-null   object
 9   Votes         1000 non-null   object
 10  Gross($)      1000 non-null   object
dtypes: object(11)
memory usage: 86.1+ KB

In [9]:
df.to_csv('MoviesDataset_Total.csv',index = None)